### ISSUE TITLE
Uncaught exception in version 0.0.13

### ISSUE THREAD

**Issue by aheitmann** [hkayann/node-red-contrib-ble-sense#8]
When starting Node-RED without a BLE device (USB dongle) present, Node-RED crashes.
This does not happen in version 0.0.12.

![blesense](https://github.com/hkayann/node-red-contrib-ble-sense/assets/110383404/5968f5c1-535b-4fd9-8510-ed4b2c0e4d8d)

**Comment by hkayann** [comment]
Hi @aheitmann ,

Could you please check if your Bluetooth controller is named as "hci0"? -> `hciconfig`

I am surprised that it works in 0.0.12. There are no changes done that would affect finding the controller.

**Comment by aheitmann** [comment]
The error only occurs if no hci device is present during the startup of NodeRed.
In my use case this can happen.

If i comment out the line "noble.on('stateChange', STATE);" in ble.js NodeRed starts without crashing.

**Comment by hkayann** [comment]
Alright, this means nothing wrong with the latest version then. Thanks for confirming.

The presence of hci device is expected before deploying the BLE nodes anyway. I might add this to `README.md`.
